<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="vasko" name="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests" tests="13" failures="0" timestamp="15 Feb 2016 10:32:53 GMT" time="95,925" errors="6">
  <testcase name="Test_updateStepsToClosure" time="10,528" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests">
    <error type="java.lang.AssertionError" message="Status Code from Post request is not as expected{&quot;error_message&quot;:&quot;A relationship could not be added: Missing id on LHS or RHS bean&quot;,&quot;error&quot;:&quot;relationship_error&quot;} expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Status Code from Post request is not as expected{"error_message":"A relationship could not be added: Missing id on LHS or RHS bean","error":"relationship_error"} expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:436)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:360)
	at com.ibm.salesconnect.API.OpportunityRestAPI.createOpportunityWithRLIreturnBean(OpportunityRestAPI.java:184)
	at com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests.Test_updateStepsToClosure(StepsToClosureRestAPITests.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Test_updateStepsToClosure -->
  <testcase name="Test_updateStepsToClosure" time="5,181" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests">
    <error type="java.lang.AssertionError" message="Status Code from Post request is not as expected{&quot;error_message&quot;:&quot;A relationship could not be added: Missing id on LHS or RHS bean&quot;,&quot;error&quot;:&quot;relationship_error&quot;} expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Status Code from Post request is not as expected{"error_message":"A relationship could not be added: Missing id on LHS or RHS bean","error":"relationship_error"} expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:436)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:360)
	at com.ibm.salesconnect.API.OpportunityRestAPI.createOpportunityWithRLIreturnBean(OpportunityRestAPI.java:184)
	at com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests.Test_updateStepsToClosure(StepsToClosureRestAPITests.java:238)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Test_updateStepsToClosure -->
  <testcase name="Test_createStepsToClosure" time="6,139" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests"/>
  <testcase name="Test_createStepsToClosure" time="7,591" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests">
    <error type="java.lang.AssertionError" message="Status Code from Post request is not as expected{&quot;error_message&quot;:&quot;A relationship could not be added: Missing id on LHS or RHS bean&quot;,&quot;error&quot;:&quot;relationship_error&quot;} expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Status Code from Post request is not as expected{"error_message":"A relationship could not be added: Missing id on LHS or RHS bean","error":"relationship_error"} expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:436)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:360)
	at com.ibm.salesconnect.API.OpportunityRestAPI.createOpportunityWithRLIreturnBean(OpportunityRestAPI.java:184)
	at com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests.Test_createStepsToClosure(StepsToClosureRestAPITests.java:167)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Test_createStepsToClosure -->
  <testcase name="Test_updateStepsToClosure" time="8,215" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests">
    <error type="java.lang.AssertionError" message="Status Code from Post request is not as expected{&quot;error_message&quot;:&quot;User \u0027fh-level10user15\u0027 is not authorized to add Steps to Closure Comment&quot;,&quot;error&quot;:&quot;not_authorized&quot;} expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Status Code from Post request is not as expected{"error_message":"User \u0027fh-level10user15\u0027 is not authorized to add Steps to Closure Comment","error":"not_authorized"} expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:436)
	at com.ibm.salesconnect.API.StepsToClosureRestAPI.createStepsToClosureHelper(StepsToClosureRestAPI.java:110)
	at com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests.Test_updateStepsToClosure(StepsToClosureRestAPITests.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Test_updateStepsToClosure -->
  <testcase name="Test_createStepsToClosure" time="7,432" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests"/>
  <testcase name="Test_createStepsToClosure" time="8,486" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests"/>
  <testcase name="Test_updateStepsToClosure" time="6,583" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests"/>
  <testcase name="Test_createStepsToClosure" time="8,986" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests"/>
  <testcase name="Test_updateStepsToClosure" time="7,463" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests"/>
  <testcase name="Test_updateStepsToClosure" time="8,413" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests">
    <error type="java.lang.AssertionError" message="Status Code from Post request is not as expected{&quot;error_message&quot;:&quot;User \u0027fh-level10user14\u0027 is not authorized to add Steps to Closure Comment&quot;,&quot;error&quot;:&quot;not_authorized&quot;} expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Status Code from Post request is not as expected{"error_message":"User \u0027fh-level10user14\u0027 is not authorized to add Steps to Closure Comment","error":"not_authorized"} expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:436)
	at com.ibm.salesconnect.API.StepsToClosureRestAPI.createStepsToClosureHelper(StepsToClosureRestAPI.java:110)
	at com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests.Test_updateStepsToClosure(StepsToClosureRestAPITests.java:245)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Test_updateStepsToClosure -->
  <testcase name="Test_createStepsToClosure" time="4,947" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests">
    <error type="java.lang.AssertionError" message="Status Code from Post request is not as expected{&quot;error_message&quot;:&quot;A relationship could not be added: Missing id on LHS or RHS bean&quot;,&quot;error&quot;:&quot;relationship_error&quot;} expected:&lt;true&gt; but was:&lt;false&gt;">
      <![CDATA[java.lang.AssertionError: Status Code from Post request is not as expected{"error_message":"A relationship could not be added: Missing id on LHS or RHS bean","error":"relationship_error"} expected:<true> but was:<false>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertTrue(Assert.java:37)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:436)
	at com.ibm.salesconnect.common.HttpUtils.postRequest(HttpUtils.java:360)
	at com.ibm.salesconnect.API.OpportunityRestAPI.createOpportunityWithRLIreturnBean(OpportunityRestAPI.java:184)
	at com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests.Test_createStepsToClosure(StepsToClosureRestAPITests.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:701)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Test_createStepsToClosure -->
  <testcase name="Test_getStepsToClosure" time="5,961" classname="com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests"/>
</testsuite> <!-- com.ibm.salesconnect.test.mobile.StepsToClosureRestAPITests -->
